import { Store } from './store';

export const RueDuCommerce: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: 'a#add-product.btn.btn--prin.add-product',
      text: [''],
    },
    maxPrice: {
      container: '.span.dyn_prod_price',
      euroFormat: true,
    },
    outOfStock: {
      container: 'a#availability-alert.price-alert',
      text: [''],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.rueducommerce.fr/produit/msi-carte-mere-b450-tomahawk-max-socket-am4-chipset-b450-84157481?articleOfferId=2639532',
    },
    {
      brand: 'asus',
      model: 'tuf 08g gaming',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394600.html',
    },
    {
      brand: 'asus',
      model: 'tuf 8g gaming',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394596.html',
    },
    {
      brand: 'asus',
      model: 'dual 08g',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394595.html',
    },
    {
      brand: 'asus',
      model: 'strix 08g gaming',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394604.html',
    },
    {
      brand: 'asus',
      model: 'dual 8g',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00393739.html',
    },
    {
      brand: 'asus',
      model: 'dual 08g mini',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00398937.html',
    },
    {
      brand: 'asus',
      model: 'dual 8g mini',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00398936.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra gaming',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394608.html',
    },
    {
      brand: 'evga',
      model: 'xc gaming',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00398042.html',
    },
    {
      brand: 'gainward',
      model: 'ghost',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394589.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394586.html',
    },
    {
      brand: 'gainward',
      model: 'ghost oc',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394590.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle 8g',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00400751.html',
    },
    {
      brand: 'gigabyte',
      model: 'master 8g',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394365.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc 8g',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394357.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc pro 8g v2',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394363.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc 8g',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394343.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc 8g',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00405704.html',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00405704.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3 rgb',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394379.html',
    },
    {
      brand: 'kfa2',
      model: 'twin x2',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394373.html',
    },
    {
      brand: 'msi',
      model: 'gaming x',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00405821.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x 8g v1',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00408782.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x 8g oc',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394150.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x 8g ocv1',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00395231.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio 8g',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394151.html',
    },
    {
      brand: 'palit',
      model: 'dual',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394602.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394434.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro oc',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394436.html',
    },
    {
      brand: 'palit',
      model: 'dual oc',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394507.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394060.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394053.html',
    },
    {
      brand: 'asus',
      model: 'dual 08g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00384225.html',
    },
    {
      brand: 'asus',
      model: 'tuf 080g gaming',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00384232.html',
    },
    {
      brand: 'asus',
      model: 'strix 08g gaming',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386904.html',
    },
    {
      brand: 'asus',
      model: 'strix 8g white',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00401655.html',
    },
    {
      brand: 'asus',
      model: '8g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00384198.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra gaming',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386927.html',
    },
    {
      brand: 'evga',
      model: 'xc3 black gaming',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386030.html',
    },
    {
      brand: 'evga',
      model: 'xc3 gaming',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386928.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra gaming',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386925.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 gaming',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386926.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385462.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385463.html',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385466.html',
    },
    {
      brand: 'gainward',
      model: 'phantom',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385465.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc 8g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00384189.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc 8g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00383549.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master 8g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385044.html',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385663.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3 rgb',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386014.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill frostbite',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00391624.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4 rgb',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386023.html',
    },
    {
      brand: 'kfa2',
      model: 'ex',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00393363.html',
    },
    {
      brand: 'kfa2',
      model: 'dual',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00393364.html',
    },
    {
      brand: 'kfa2',
      model: 'sg',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385058.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio 8g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385048.html',
    },
    {
      brand: 'msi',
      model: 'gaming trio 8g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00408781.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x 8g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00408869.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x 8g oc',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385046.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x 8g oc',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385045.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x 8g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00408780.html',
    },
    {
      brand: 'msi',
      model: 'suprim x 8g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00391681.html',
    },
    {
      brand: 'msi',
      model: 'suprim 8g',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00395874.html',
    },
    {
      brand: 'palit',
      model: 'jetStream oc',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385132.html',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385128.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385126.html',
    },
    {
      brand: 'palit',
      model: 'gameRock oc',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385129.html',
    },
    {
      brand: 'palit',
      model: 'jetstream',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385131.html',
    },
    {
      brand: 'palit',
      model: 'gamingPro oc',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385127.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00383541.html',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc white edition',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00398664.html',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00401469.html',
    },
    {
      brand: 'asus',
      model: 'tuf 10g gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368789.html',
    },
    {
      brand: 'asus',
      model: 'tuf 010g gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368844.html',
    },
    {
      brand: 'asus',
      model: 'strix 010g gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385535.html',
    },
    {
      brand: 'asus',
      model: 'strix 10g gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375431.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369303.html',
    },
    {
      brand: 'evga',
      model: 'xc3 black gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369298.html',
    },
    {
      brand: 'evga',
      model: 'xc3 gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369268.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra hybrid gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398045.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra hybrid gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398046.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369299.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 gaming',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369265.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369150.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369158.html',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00390727.html',
    },
    {
      brand: 'gainward',
      model: 'phantom',
      series: '3080',
      url: 'https://www.ldlc.com/fiche/PB00386063.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc 10g',
      series: '3080',
      url: 'https://www.ldlc.com/fiche/PB00368968.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc 10g',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369072.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master 10g',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00376208.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme 10g',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00390466.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce 10g',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398370.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle 10g',
      series: '3080',
      url: 'https://www.ldlc.com/fiche/PB00400753.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc 10g',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00376207.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb 10g',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398373.html',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368690.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3 rgb',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368691.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill frostbite',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00391624.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4 rgb',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368692.html',
    },
    {
      brand: 'kfa2',
      model: 'ex gamer',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00396037.html',
    },
    {
      brand: 'kfa2',
      model: 'sg',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368931.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio 10g',
      series: '3080',
      url: 'https://www.ldlc.com/fiche/PB00368574.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x 10g oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368506.html',
    },
    {
      brand: 'msi',
      model: 'suprim x 10g',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00391682.html',
    },
    {
      brand: 'palit',
      model: 'gamingPro',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369094.html',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386334.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375448.html',
    },
    {
      brand: 'palit',
      model: 'gameRock oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386332.html',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375625.html',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368579.html',
    },
    {
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375644.html',
    },
    {
      brand: 'asus',
      model: '024g gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374911.html',
    },
    {
      brand: 'asus',
      model: 'tuf 24g gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00369842.html',
    },
    {
      brand: 'asus',
      model: 'strix 024g gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00369849.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374631.html',
    },
    {
      brand: 'evga',
      model: 'xc3 black gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374629.html',
    },
    {
      brand: 'evga',
      model: 'xc3 gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374628.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra hybrid gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00398039.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra hybrid gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00398037.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374837.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374838.html',
    },
    {
      brand: 'evga',
      model: 'kingpin hybrid gaming',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00398044.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00370903.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00370913.html',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00390227.html',
    },
    {
      brand: 'gainward',
      model: 'phantom',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00390729.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc 24g',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00371131.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc 24g',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00371132.html',
    },
    {
      brand: 'gigabyte',
      model: 'turbo 24g',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00391621.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme 24g',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00390730.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce 24g',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00398364.html',
    },
    {
      brand: 'gigabyte',
      model: 'master 24g',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00376302.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc 24g',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00386908.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb 24g',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00400756.html',
    },
    {
      brand: 'inno3d',
      model: 'gaming x3',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00371280.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill frostbite',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00391541.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3 rgb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374606.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4 rgb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374614.html',
    },
    {
      brand: 'kfa2',
      model: 'hof',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00407277.html',
    },
    {
      brand: 'kfa2',
      model: 'sg',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00371133.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio 24g',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00370065.html',
    },
    {
      brand: 'msi',
      model: 'ventus 3x 24g oc',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00370057.html',
    },
    {
      brand: 'msi',
      model: 'suprim x 24g',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00391683.html',
    },
    {
      brand: 'palit',
      model: 'gamingPro',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374912.html',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00389189.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro oc',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374914.html',
    },
    {
      brand: 'palit',
      model: 'gameRock oc',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00391625.html',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00370250.html',
    },
    {
      brand: 'zotac',
      model: 'trinity oc',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00401472.html',
    },
  ],
  name: 'rueducommerce',
};
